#!/bin/sh

if [ -r /sys/devices/virtual/dmi/id/product_name ] && grep -q '^20CD0038MN$' /sys/devices/virtual/dmi/id/product_name; then
	echo "Running on a ThinkPad S1 Yoga laptop"
	dock_left="DP1-1"
	dock_center="DP1-2"
	builtin_display="eDP1"

	xrandr --output "$builtin_display" --auto
	xrandr --output "$dock_center" --auto
	xrandr --output "$dock_left" --auto

	dock_center_connected=	
	dock_left_connected=	
	builtin_display_connected=

	if xrandr --query|grep -q "^$dock_center connected"; then
		dock_center_connected=y
	fi
	if xrandr --query|grep -q "^$dock_left connected"; then
		dock_left_connected=y
	fi

	if [ -n "$dock_center_connected" ] && [ -n "$dock_left_connected" ]; then
		echo "Docked with both external displays connected"
		xrandr --output "$builtin_display" --rotate normal
		xrandr --output "$dock_center" --left-of "$builtin_display"
		xrandr --output "$dock_left" --left-of "$dock_center" --rotate left
		xbacklight -set 100
	elif [ -z "$dock_center_connected" ] && [ -z "$dock_left_connected" ]; then
		echo "Not docked"
		xrandr --output "$builtin_display" --rotate normal
		xrandr --output "$dock_center" --off
		xrandr --output "$dock_left" --off
		#xbacklight -set 100
	elif [ -n "$dock_center_connected" ] && [ -z "$dock_left_connected" ]; then
		echo "Docked with center display connected but left display disconnected"
		xrandr --output "$builtin_display" --rotate normal
		xrandr --output "$dock_center" --left-of "$builtin_display"
		xrandr --output "$dock_left" --off
		xbacklight -set 100
	elif [ -z "$dock_center_connected" ] && [ -n "$dock_left_connected" ]; then
		echo "Docked with center display disconnected, but left display connected"
		xrandr --output "$builtin_display" --rotate normal
		xrandr --output "$dock_center" --off
		xrandr --output "$dock_left" --left-of "$builtin_display" --rotate left
		xbacklight -set 100
	else
		echo "No idea how to organize this display setup" >&2
	fi
else
	echo "Not sure what kind of machine this is. Skipping monitor layouts"
fi
