#!/bin/bash

ordered() {
	order=( "${@}" )

	xrandr --output "${order[0]}" --auto
	let end=${#order[@]}-1
	for i in $(seq 1 $end); do
		let ii=i-1
		xrandr --output "${order[$i]}" --auto --right-of "${order[$ii]}"
	done
}

set_primary() {
	xrandr --output "$1" --primary
}

if [ -r /sys/devices/virtual/dmi/id/product_name ] && grep -q '^20CD0038MN$' /sys/devices/virtual/dmi/id/product_name; then
	echo "Running on a ThinkPad S1 Yoga laptop"
	ordered "eDP1" "HDMI2"
	set_primary "eDP1"
elif [ -r /sys/devices/virtual/dmi/id/product_name ] && grep -q '^MS-7C80$' /sys/devices/virtual/dmi/id/product_name; then
	echo "Running on desktop"
	xrandr --output 'HDMI-1' --rotate normal
	ordered 'HDMI-1' 'DP-1'
	set_primary 'DP-1'
elif [ "$(hostname)" = "jesper-pc-linux" ]; then
	echo "Running on $(hostname)"
	ordered "HDMI-0" "DP-0" "DP-4"
	ordered "DP-0.1" "DP-0.8" "DP-4"
	if xrandr --listmonitors|awk '$4 != "" { print $4}'|grep -q "HDMI-0" && xrandr --listmonitors|awk '$4 != "" { print $4}'|grep -q "DP-0"; then
		echo "Running in home office"
		xrandr --output DP-0 --rotate inverted
		set_primary "HDMI-0"
	else
		xrandr --output DP-0 --rotate normal
		set_primary "DP-0.8"
	fi
else
	echo "Not sure what kind of machine this is. Skipping monitor layouts"
fi

