# Prevents certain popups from "shining through" i3lock:
# https://github.com/i3/i3lock/issues/22#issuecomment-703243117
# Another option to consider might be setting _NET_WM_BYPASS_COMPOSITOR on the i3lock window:
# https://github.com/yshui/picom/issues/576#issuecomment-754242727
unredir-if-possible = true;

vsync = true;
backend = "xrender";
