#!/bin/sh
set -euo pipefail

DISPLAYNAME="${DISPLAYNAME:-eDP-1}"

rotate() {
	orientation="$1"
	xrandr --output "$DISPLAYNAME" --rotate "$orientation"

	for wacom_name_path in /sys/bus/hid/drivers/wacom/*/input/*/name; do
		# If the glob didn't match anything, there are no applicable Wacom devices
		if ! [ -f "$wacom_name_path" ]; then
			break
		fi
		while read -r wacom_partial_name; do
			xinput list --name-only \
			| grep -F "$wacom_partial_name" \
			| while read -r wacom_name; do
				xinput map-to-output "$wacom_name" "$DISPLAYNAME"
			done
		done < "$wacom_name_path"
	done
}

monitor-sensor | while read -r line; do
    case "$line" in
        *normal*)
		rotate normal
            ;;
        *left-up*)
            rotate left
            ;;
        *right-up*)
            rotate right
            ;;
        *bottom-up*)
            rotate inverted
            ;;
    esac
done
