#!/bin/sh
set -euo pipefail

monitor="eDP-1"

for device in \
	'Wacom HID 52EB Pen stylus' \
	'Wacom HID 52EB Finger touch' \
	'Wacom HID 52EB Pen eraser'
do
	if xinput | grep -qF "$device"; then
		xinput map-to-output "$device" "$monitor"
	fi
done
