#!/bin/bash
# Moves focused window to another workspace
if [ $# -eq 0 ]; then
	i3-msg -t get_workspaces|jq -r '.[].name'|sort -n
else
	i3-msg move workspace "$*" >/dev/null
	i3-msg workspace "$*" >/dev/null
fi
